### PR TITLE
Updated layout and added auto hide for output menu options

### PR DESCRIPTION
**Pull request by chimmyten**
Changed the layout of the output menu options to vertical and put them on top of the output box. The menu options will only appear when the user's mouse hovers on the output box.

### CODE REVIEW

**Comment by lihebi** [comment]
Thanks, Timmy!

Two things:
1. Can you use [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) (with default config) to format your code? So that
   1. the code is consistent with our code base, and
   2. make sure the diff contains exactly the changes you made for easier review.
3. Please attach a screenshot here to easily see the new UI

**Comment by chimmyten** [comment]
No problem, I'll work on fixing that.

**Comment by lihebi** [comment]
You can just push to this branch , it will automatically update this PR.

**Comment by chimmyten** [comment]
Auto Hide Menu Changes

The new UI.
Please let me know if I need to make additional changes.

**Comment by lihebi** [comment]
Great PR. Thanks, Timmy!

**Comment by forrestbao** [comment]
Thanks @chimmyten. But the three options should appear in the output box instead of the code part.  

> Auto Hide Menu Changes
> 
> The new UI. Please let me know if I need to make additional changes.

**Comment by lihebi** [comment]
We had a discussion in #321 about the menu position.

**Pull request merged**
