### PR TITLE
Add developer Onboarding doc

### PR DESCRIPTION
**Pull request by senwang86**
- A summary of the development framework, repo brief description and system architecture.

### CODE REVIEW

**Comment by lihebi** [comment]
Thanks!

One general thinking: should we put documentation on [our website](https://codepod.io)? It's easier and more organized for people to access.

The website repo is: https://github.com/codepod-io/codepod.io

**Comment by lihebi** [comment]
E.g., this is the user manual page: https://codepod.io/docs/manual/
this is the developer manual page: https://codepod.io/docs/developer/

**Comment by lihebi** [comment]
I'm thinking about putting all documents (including the dev env setup in the root README) to the website repo, and maintain the docs there. We could leave a link to the user manual and developer manual in the README of this repo. What do you think? @forrestbao

**Comment by senwang86** [comment]
> Thanks!
> 
> One general thinking: should we put documentation on [our website](https://codepod.io)? It's easier and more organized for people to access.
> 
> The website repo is: https://github.com/codepod-io/codepod.io

Sounds good, here's the PR for the website change, https://github.com/codepod-io/codepod.io/pull/8

**Comment by forrestbao** [comment]
> I'm thinking about putting all documents (including the dev env setup in the root README) to the website repo, and maintain the docs there. We could leave a link to the user manual and developer manual in the README of this repo. What do you think? @forrestbao

I agree. But do not put business sensitive information there. Only those we want to make it public.

**Comment by senwang86** [comment]
OK, I will close this PR and start another one on the website repo.

**Comment by senwang86** [comment]
Drop this PR and please refer https://github.com/codepod-io/codepod.io/pull/8 for the changes.

**Pull request closed without merging**
