### PR TITLE
contextual zoom initial font size reduction

### LINKED ISSUE #316: Font size for summaries in contextual zooming
The font size for summaries in contextual zoom maybe initially too big. See the video below. 
The initial font when pods collapsed is even bigger than the code/comment in the pods right before the collapse. In the video, when zoomed out, the font size jumped up when the pods collapsed. 

https://github.com/codepod-io/codepod/assets/438579/29cd1175-ecad-4f0a-b2d8-63da5593ffb0

### PR DESCRIPTION
**Pull request by chimmyten**
When a pod is initially collapsed, the font size for the contextual zoom summary will be smaller. When the canvas is zoomed out past a certain point, the font size of the summary will increase to the previous set size. Fixes #316. 

https://github.com/codepod-io/codepod/assets/105993789/5120bd62-19d6-4384-a903-31a1b8944214

### CODE REVIEW

**Comment by lihebi** [comment]
How about let's make the `contextualZoomParams` configurable? That is, add a setting in the sidebar allowing users to  override these numbers (which are the expected font sizes for each level).

https://github.com/codepod-io/codepod/blob/0f1b143cb555edfbbc56bacb4932fc4272a92f79/ui/src/lib/store/settingSlice.tsx#L78-L87

**Comment by lihebi** [comment]
Also, note that the same code (for computing and setting fonts) is used in three places: `Code.tsx`, `Rich.tsx`, `Scope.tsx`. We might want to make them with reasonable font size.

https://github.com/codepod-io/codepod/blob/0f1b143cb555edfbbc56bacb4932fc4272a92f79/ui/src/components/nodes/Code.tsx#L581-L590

https://github.com/codepod-io/codepod/blob/0f1b143cb555edfbbc56bacb4932fc4272a92f79/ui/src/components/nodes/Rich.tsx#L769-L776

https://github.com/codepod-io/codepod/blob/0f1b143cb555edfbbc56bacb4932fc4272a92f79/ui/src/components/nodes/Scope.tsx#L225-L235

**Comment by lihebi** [comment]
This setting-in-sidebar thing sounds like another PR. Feel free to work on it and submit another PR if you find fit.

**Comment by chimmyten** [comment]
Sounds good, I'll work on implementing that.

**Pull request closed without merging**
