### PR TITLE
Apply "Show Line Numbers" as toggle switch in sidebar

### PR DESCRIPTION
**Pull request by senwang86**
- Add the toggle switch in sidebar
- remove the menu item from Right Click menu.
- 
showLineNumbers

### CODE REVIEW

**Comment by lihebi** [comment]
Awesome, thanks!

**Comment by forrestbao** [comment]
Thanks Sen.  A minor bug. Once "show line" is re-enabled, the last-run info goes missing.

**Comment by lihebi** [comment]
> A minor bug. The last-run timer goes missing sometimes after "show line" is re-enabled.

This isn’t possible. You might have miss-interpreted the video.

**Comment by senwang86** [comment]
> Thanks Sen. A minor bug. The last-run timer goes missing sometimes after "show line" is re-enabled.

Do you mind sharing a screen shot of the bug? I tried it a couple of times but didn't reproduce on my end.

**Comment by forrestbao** [comment]
> > Thanks Sen. A minor bug. The last-run timer goes missing sometimes after "show line" is re-enabled.
> 
> Do you mind sharing a screen shot of the bug? I tried it a couple of times but didn't reproduce on my end.

It's in your video above. Toward the end, when kernel up time is 35m21s 
image

**Comment by senwang86** [comment]
> > > Thanks Sen. A minor bug. The last-run timer goes missing sometimes after "show line" is re-enabled.
> > 
> > 
> > Do you mind sharing a screen shot of the bug? I tried it a couple of times but didn't reproduce on my end.
> 
> It's in your video above. Toward the end, when kernel up time is 35m21s image

Is it because of auto replay? In terms of "Uptime", the recording begins at 35m11s and ends at 35m28s.

**Pull request merged**
