### PR TITLE
don't set name on start when data.name is undefined

### PR DESCRIPTION
**Pull request by lihebi**
setPodName caused sync on page refresh. This PR fixes it.

### CODE REVIEW

**Comment by li-xin-yi** [comment]
What if a user clear the pod name (make it empty)?

**Comment by lihebi** [comment]
I think this condition only checks for undefined value but not empty string. Please see if that’s a problem, and if so let’s check data.name === pod.name as well.

**Comment by li-xin-yi** [comment]
I introduced a check in previous PR (https://github.com/codepod-io/codepod/blob/main/ui/src/lib/store.tsx#L458), to mark a pod dirty, we may first check if the value is actually updated.

**Comment by lihebi** [comment]
> I introduced [a check in previous PR](https://github.com/codepod-io/codepod/blob/main/ui/src/lib/store.tsx#L458), to mark a pod dirty, we may first check if the value is actually updated.

Yes, this looks good.

**Pull request merged**
