### PR TITLE
feat: support naming on pod and scope

### LINKED ISSUE #97: Allowing naming pods and scopes
Add a small box at the headbar of a pod or scope where users can click and name a pod or a scope. 

This will help code management and visualization. 

What do you think? @lihebi

### PR DESCRIPTION
**Pull request by pionxzh**
closes #97

long text will become an ellipsis.
image

We can further improve some of the controlling behaviors around this name input field. (hint, style, arrow key navigation)

### CODE REVIEW

**Comment by forrestbao** [comment]
@pionxzh what do you mean by hint and style? 
I love the arrow key idea.

**Comment by pionxzh** [comment]
> How do we intend to manage the name state?
> 
> It seems that you only maintain the pod names during one-time visit life-cycle in this PR.
> 
> I just wonder which mode we should design
> 
> - keep the consistent pod names for all users all the time ( sync by DB and yjs server)
> - or, let each user tags the pod with their preferred name even in one same repo
> - or, reset the pod names by default after refreshing
> 
> It involves some back-end DB and yjs server works. I can work on it after we agree on either mode.

Good point. Actually I didn't check did it really get persisten to the DB or not, but it did remember my changes after reloading.

I prefer the idea of syncing pod name to DB and YJS.

**Review by lihebi — APPROVED** [review]
Great feature, thanks Pionxzh!

**Comment by forrestbao** [comment]
@pionxzh the arrow key idea was mentioned here: https://github.com/codepod-io/codepod/issues/87 I will temporarily assign to you.

**Pull request merged**
