### PR TITLE
fix: #98

### PR DESCRIPTION
**Pull request by fundon**
Color taken from from https://mui.com/material-ui/customization/color/#main-content.

Screenshot 2022-12-09 at 10 04 40 PM

Screenshot 2022-12-09 at 10 02 21 PM

### CODE REVIEW

**Comment by lihebi** [comment]
Thanks! I don't have too much opinion on the theming. @forrestbao does this coloring look good to you?

**Review by lihebi — COMMENTED** [review]
Looks like we are using different formatter. Can you try to re-format using [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)?

**Comment by forrestbao** [comment]
> Thanks! I don't have too much opinion on the theming. @forrestbao does this coloring look good to you?

Thanks for asking for my opinion @lihebi. Let's leave the color like that for now until we have a chance to consult a designer. 

@fundon does the infill color gradually darkens as the nested level of scopes increases?

**Comment by fundon** [comment]
> @fundon does the infill color gradually darkens as the nested level of scopes increases?

Currently defines 4 levels.  

It may be more intuitive to have a prototype design

https://github.com/codepod-io/codepod/pull/130/files#diff-c77756d2a50928e8e187ebede6a09ee0bcde46f7035ce4362b892fe3986d285bR559-R565

Screenshot 2022-12-10 at 10 37 38 AM

**Review by lihebi — APPROVED** [review]
Thanks Fangdun!

**Comment by forrestbao** [comment]
@fundon In the screenshot above, a scope box has a window like that of a code cell. But in the deployed code, a scope box still uses the the Windows 95 style. Did you forget to add the code for the frame style change?

**Pull request merged**
