### PR TITLE
refactor: sidebar and header

### PR DESCRIPTION
**Pull request by nibilin33**
issues[75](https://github.com/codepod-io/codepod/issues/75)
final effect
t-rec

### CODE REVIEW

**Comment by lihebi** [comment]
Looking great! Now the sidebar cannot be pinned. But some information are supposed to be available to the users all the time:
- the cloud saving status
- the kernel status

Screenshot 2022-11-25 at 6 46 11 PM

Let's implement the same UI for saving status as Google Docs:

Screenshot 2022-11-25 at 6 49 30 PM

And the kernel status as Colab:

Screenshot 2022-11-25 at 6 51 31 PM

@forrestbao any thoughts?

**Comment by forrestbao** [comment]
let's study Deepnote's UI. It does not show whether it's saving to the cloud (because it is supposed to) nor show whether a kernel is connected on the side bar -- if it is not connected, it will show a hovered notification. I like this design actually. 

So why don't we move things that are in the side bar to the top bar? Given that the top bar is not crowded and we have only a couple of items in the side bar? 

image

**Comment by lihebi** [comment]
>  nor show whether a kernel is connected on the sidebar -- if it is not connected, it will show a hovered notification.
Deepnote does always show the kernel status, both in the sticky top bar, as well as in the right bar.

I think the "saved to cloud" feedback gives users more confidence. I prefer to have it as well, just like Google Docs and Feishu Docs.

Lastly, the sidebar in this PR cannot be pinned: you cannot have it while coding. Let's change it to a pinnable sidebar instead, like [this](https://mui.com/material-ui/getting-started/templates/dashboard/).

Screenshot 2022-11-25 at 11 29 15 PM

**Comment by lihebi** [comment]
To summarize, here're my requests:
- show the cloud-saving status all the time (next to the breadcrumb)
- show the kernel status all the time (on a sticky top bar?)
- make the sidebar pinnable (and make it show by default?)

**Comment by nibilin33** [comment]
if these informations move to other places, it seems there is no need for sidebar?

**Comment by nibilin33** [comment]
if these informations move to other places, it seems there is no need for sidebar?

**Comment by lihebi** [comment]
We will have more items in the sidebar soon. So let’s keep the sidebar.

**Comment by forrestbao** [comment]
So what's the status of this? I simply wanted to maximize the canvas area. It was too small on my 13-inch laptop. 

Side bar is usually foldable, holding information that is not constantly needed. 
So I suggest we move information that users need to see constantly to the top bar. 

@lihebi ?

**Comment by forrestbao** [comment]
>     * make the sidebar pinnable (and make it show by default?)

@nibilin33  I talked with Hebi. He wants the sidebar to remain open until a user closes it, and I agree with it. In DeepNote, the sidebar remains there until a user closes it. 

I read the code. You used Material UI's `<Drawer  />` It actually has a persistent mode which perfectly meet Hebi's needs. 

https://mui.com/material-ui/react-drawer/#persistent-drawer

Additionally, in the demos of persistent drawer in the link above, the draw does not overlay above the "main page" nor the top bar. This is the behavior we expect.

**Comment by nibilin33** [comment]
* make the sidebar pinnable (and make it show by default?)
this way needs totally rewrite,header is global share. it will take a lot time. I will just commit header breadcrams firstly

**Comment by lihebi** [comment]
> make the sidebar pinnable (and make it show by default?)
> this way needs totally rewrite

The previous sidebar is pinnable and shows by default. I think what @forrestbao wants is to change the text "hide" and "show" to some icons.

Screenshot 2022-11-29 at 10 14 19 AM

**Comment by lihebi** [comment]
> header is global share

But yes, I agree this needs more code and design to pass repo states to the header. Move this discussion to #105.

**Pull request closed without merging**
